"""Add quantity to order_items

Revision ID: 3d768aed2206
Revises: 594200415b32
Create Date: 2025-12-10 22:36:12.844322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d768aed2206'
down_revision: Union[str, Sequence[str], None] = '594200415b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_user_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    op.drop_column('order_items', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quiantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'quantity')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_user_id_fkey'), 'cart_items', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('cart_items_product_id_fkey'), 'cart_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
